blog/urls.py
from django import views
from django.urls import path
from .views import render_post, post_detail
# import views

# Para referenciar todas las url utilizamos el nombre de una variable, post visita <url patterns>

app_name= 'blog'

urlpatterns = [
    path('', render_post, name='posts'),
    path('<int:post_id>', post_detail, name='post_detail'),
    
]

django_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls')),
] 

# Permite ver las imagenes al compartir la url
urlpatterns+= static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)

blog/models.py
from django.db import models
import datetime

# Create your models here.
class Post(models.Model):
    #Mostrar el titulo en admin site - NO como objeto

    def __str__(self):
        return self.title

    title = models.CharField(max_length=100)
    description = models.TextField()#contenido mas grande
    image = models.ImageField(upload_to='blog/images')
    date = models.DateField(datetime.date.today)

portfolio/models.py
from django.db import models
from django.db.models.fields import CharField, URLField
from django.db.models.fields.files import ImageField


# Create your models here.
class Project(models.Model):

    #Mostrar el titulo en el admin site, NO como objeto
    def __str__(self):
        return self.title

    title =  CharField(max_length=100)
    description = CharField(max_length=250)
    image = ImageField(upload_to='portfolio/images/')
    url = URLField(blank=True)

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
#intenta obtener un objeto si no muestra 404 get_objet_or_404
# Create your views here.
def render_post(request):

    posts = Post.objects.all()
    return render(request,'post.html', {'posts': posts})

def post_detail(request, post_id):

    post = get_object_or_404(Post, pk=post_id)

    return render(request, 'post_detail.html', {'post':post})

portfolio/views.py
from django.shortcuts import render
from .models import Project

# Create your views here.
def home(request):

    #traer de la base de datos
    projects = Project.objects.all()

    return render(request, 'home.html', {'projects':projects})

blog/templates/post.html
{% extends 'layout.html' %}

{% block content %}
<h1>POST</h1>

<!--
    safe interpreta etiquetas escritas desde el admin
    striptags quita las etiquetas y deja el texto
    truncatechars:<num> solo muestra hasta num de texto
-->
{% for post in posts %}

<div class="p-3">
    <div class="card card-body bg-dark bg-gradient">

        <div class="row">
            <div class="col-3">
                <img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid">
            </div>
    
            <div class="col-9">
                <h2>{{post.title}}</h2>
                <p>{{post.description|striptags |truncatechars:100}}</p>
                <p>{{post.date|date:'M d Y'}}</p>
    
                <a href="{% url 'blog:post_detail' post.id %}" class="btn btn-primary">{{post.title}}</a>
            </div>
        </div>
    </div>
</div>
{% endfor %}

{% endblock %}

blog/templates/post_detail.html
{% extends 'layout.html' %}

{% block content %}

<!--
    safe interpreta etiquetas escritas desde el admin
    striptags quita las etiquetas y deja el texto
    truncatechars:<num> solo muestra hasta num de texto
-->



<div class="text-center">
    <h2>{{post.title}}</h2>
    <img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid">
    <h3 class="my-3 h5 text-muted">{{post.date}}</h3>
    
    <div class="my-4">
        <p>{{post.description|safe}}</p>
    </div>

</div>


{% endblock %}

portfolio/templates/home.html
{% extends 'layout.html' %}


{% block content %}

{% load static %}

<header class="row">
    <div class="col-md-4">
        <img src="{% static 'portfolio/profile.jpeg' %}" alt="">
    </div>
    <div class="col-md-8">
        <h1>I am <strong>Emher</strong></h1>
        <h3>I am a Python developer</h3>
        <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Impedit obcaecati velit, repellendus officia libero
            ipsum
            quam exercitationem ex maiores culpa? Culpa ducimus ipsum quaerat nihil accusantium illo? Enim itaque aut
            molestiae.
            Temporibus animi voluptatum obcaecati itaque et aliquam at, quae, molestiae architecto in praesentium
            adipisci
            veniam consequuntur magnam culpa? Consequuntur, qui? Deleniti eligendi quo facilis et suscipit voluptas
            velit
            temporibus. Distinctio assumenda consequatur deleniti nisi consectetur magnam a natus eius doloremque!
            Aliquam
            distinctio architecto doloribus nulla maiores fuga ducimus unde deserunt id recusandae odio consequuntur cum
            assumenda magni at, sequi inventore nam! Similique explicabo minima tenetur eveniet facere ipsum voluptate.
        </p>
        <a href="{% static 'portfolio/cv.pdf' %}" class="btn btn-primary btn-lg rounded-0 my-3">Download CV</a>
    </div>
</header>

<div class="row">
    <h3>My projects</h3>
    <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Explicabo fuga praesentium voluptas cum magni
        voluptatem
        odit est labore eos vel! Provident molestias fugiat possimus atque porro in quisquam deleniti delectus!</p>
    

    {% for project in projects %}

    <div class="col-md-4 p-4">
        <div class="card bg-dark card-project">
            <img src="{{project.image.url}}" alt="{{project.title}}" class="card-img-top">
            <div class="card-body">
                <h2>{{project.title}}</h2>
                <p>{{project.description}}</p>

                {% if project.url %}

                <a class="btn btn-light btn-sm" target="_blank" href="{{project.url}}">{{project.url}}</a>
                {% endif%}

            </div>
        </div>

    </div>
    {% endfor %}

</div>

{% endblock%}

portfolio/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django Portfolio</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<!--
No carga esta ruta
<link rel="stylesheet" href="{% static 'portfolio/css/main.css' %}">
-->
    <link rel="stylesheet" href="{% static 'portfolio/main.css' %}">

</head>
<body class="bg-dark text-white">
    {% include 'partials/_navbar.html' %}

    <div class="container p-4">

        {% block content%}
        {% endblock %}
    </div>    

    
</body>
</html>

portfolio/templates/partials/_navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand fw-bold" href="/">Emher</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="" href="{% url 'blog:posts' %}">Blog</a>
                </li>
                <li class="nav-item d-flex align-items-center">
                    <a class="btn btn-primary btn-sm" href="{% static 'portfolio/cv.pdf' %}" target="_blank">Download
                        CV</a>
                </li>

            </ul>
        </div>
    </div>
</nav>